### ISSUE TITLE
Change health and AC using a popover

### ISSUE THREAD

**Issue by SeamusFinlayson** [kamejosh/owlbear-hp-tracker#12]
I would appreciate if I or a player could edit a token's health and and AC using a popover kinda like in the token counter extension as shown below.
![image](https://github.com/kamejosh/owlbear-hp-tracker/assets/77430559/103e27c8-0e8a-4268-b002-55284efaefce)
I saw that you added extra buttons to the context menu to increment and decrement health but it's kinda difficult to click 29 times. I think a context menu with field that I could edit would be easier to use. Just putting these 3 boxes in would be great.
![image](https://github.com/kamejosh/owlbear-hp-tracker/assets/77430559/53893fdf-31bb-4fee-b6e2-a30176fa2521)
Maybe something like...
![image](https://github.com/kamejosh/owlbear-hp-tracker/assets/77430559/17c1b271-853e-40d6-840b-6316e27d03ce)

**Comment by kamejosh** [comment]
The Popover came with lots of Problems in syncing input fields between all the different viewports I had and greatly decreased performance (also might be due to bugs in my code but not having the popover removed all the bugs 😁 ).

I honestly think it would be a lot easier for you (if you have enough screenspace) to undock the HP Tracker extension and edit the values in the input field already available. 

I also do not show the HP+ and HP- options in the context menu for players because I don't want them to accidentally click them. Going into the HP Tracker window and editing the values is a much more conscious decision, which prevents mistakes. But I will think a little bit about it to see if I can come up with something. Meanwhile I would be very happy if you could give the Main HP Tracker window a try and tell me if it works for you (I added charactersheets for monsters available in open5e in the latest update 😉 ).

**Comment by kamejosh** [comment]
I just saw that this is still open. In the meantime you created your own extension and I added the popover back in 😁
