### ISSUE TITLE
Trouble seeing updated health bar on Owlbear HP-Tracker

### ISSUE THREAD

**Issue by DoggoDoesaDash** [kamejosh/owlbear-hp-tracker#40]
Hi,

I've been having this issue for awhile now, and it's rather small, but it seems whenever I go to update a creature/monster's HP the HP bar doesn't update. I usually have to hide the bar and reveal it for it to work.  Then sometimes it just outright won't work. 

I'm currently on chrome if that helps. 

Thanks,

Jordan

**Comment by kamejosh** [comment]
interesting, I can't reproduce it, and it should absolutely not be the case. I need to look at the room in question, could you write me on discord: username is `kamejosh` because I need in invite to the room, and I don't want to do this all publicly. You could also write to me here: https://discord.com/channels/795808973743194152/1136777520868507728

**Comment by DoggoDoesaDash** [comment]
Sure thing,

My discord user name is DoggoDoesaDash

Gonna get some sleep but i’ll send u an invite to the room. Do u need any
permissions once in owlbear?
